apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }} 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.aws.account_id }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.stage }}-{{ .Values.name }}:{{ .Values.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-nodeport-service
  labels:
    app: {{ .Values.name }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /{{ .Values.endpoint.health }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.name }}